// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAOjs9Qhu5QCqF2B23vMX-uw29LTQsg4sc",
    authDomain: "neurospark-cf205.firebaseapp.com",
    projectId: "neurospark-cf205",
    storageBucket: "neurospark-cf205.firebasestorage.app",
    messagingSenderId: "773865468608",
    appId: "1:773865468608:web:ec514e8823df4bdfdb3325",
    measurementId: "G-JN47RV3HEM",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForDevelopment-ReplaceWithReal',
    appId: '1:123456789:android:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'neurospark-demo',
    authDomain: 'neurospark-demo.firebaseapp.com',
    storageBucket: 'neurospark-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForDevelopment-ReplaceWithReal',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'neurospark-demo',
    authDomain: 'neurospark-demo.firebaseapp.com',
    storageBucket: 'neurospark-demo.appspot.com',
    iosBundleId: 'com.neurospark.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForDevelopment-ReplaceWithReal',
    appId: '1:123456789:macos:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'neurospark-demo',
    authDomain: 'neurospark-demo.firebaseapp.com',
    storageBucket: 'neurospark-demo.appspot.com',
    iosBundleId: 'com.neurospark.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForDevelopment-ReplaceWithReal',
    appId: '1:123456789:windows:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'neurospark-demo',
    authDomain: 'neurospark-demo.firebaseapp.com',
    storageBucket: 'neurospark-demo.appspot.com',
  );
}
